### ISSUE TITLE
*.stl's are all damaged

### ISSUE THREAD

**Issue by Osmodia666** [P1ayer2/CZ-300_On_Steroids#4]
Hi, all of the *.stl Files from your Mods are damaged, they can't be opened in PrusaSlicer, Bambu Studio or Fusion360. 
I would appreciate if you could check this and reupload the files, thank you!

**Comment by navil-hossain** [comment]
Hey there! 

I'll make sure to take a look. Worst case scenario, I'll upload them to thingiverse and post the links.

**Comment by jnorre** [comment]
I just tried downloading a STL from the PSU mount folder and from the vibrationdamper folder (just two random STL files) and were able to open both in Cura, Orca Slicer and Prusa Slicer - all newest or a very recent version and all on Ubuntu 22.04. Make sure you download the whole repository as a ZIP file (or clone it) - if you download the files directly from github, you need to download the "RAW file" - click the STL file on github and use the download button over the preview at the right to download the raw file. If you right click a file and use "Save as" in the folder view, you do NOT get a working file. Try it and let us know if it works!

**Comment by Osmodia666** [comment]
> I just tried downloading a STL from the PSU mount folder and from the vibrationdamper folder (just two random STL files) and were able to open both in Cura, Orca Slicer and Prusa Slicer - all newest or a very recent version and all on Ubuntu 22.04. Make sure you download the whole repository as a ZIP file (or clone it) - if you download the files directly from github, you need to download the "RAW file" - click the STL file on github and use the download button over the preview at the right to download the raw file. If you right click a file and use "Save as" in the folder view, you do NOT get a working file. Try it and let us know if it works!

Thats what I did, cause if I click on download RAW File nothing happens. Neither with Firefox, Chrome or Edge. 
I can only download the whole Repository, that worked for me.
